/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package christmasshopping;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author x19501339
 */
public class ChristmasShoppingGUI extends javax.swing.JFrame {
    private String Name;
    private String Gift;
    private String Url;

    /**
     * Creates new form ChristmasShoppingGUI
     */
    public ChristmasShoppingGUI() {
        initComponents();
        Name = "";
        Gift = "";
        Url = "";
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        Giftlbl = new javax.swing.JLabel();
        Namelbl = new javax.swing.JLabel();
        Urllbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        List1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        Textarea2 = new javax.swing.JTextArea();
        Addbtn1 = new javax.swing.JButton();
        NameText1 = new javax.swing.JTextField();
        UrlText1 = new javax.swing.JTextField();
        Ideatext = new javax.swing.JLabel();
        IdeadText2 = new javax.swing.JLabel();
        Idea2 = new javax.swing.JLabel();
        Ideatext2 = new javax.swing.JLabel();
        Delete = new javax.swing.JButton();
        Delete2 = new javax.swing.JButton();
        Addbtn2 = new javax.swing.JButton();
        DisplayBtn1 = new javax.swing.JButton();
        DisplayBtn2 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Giftlbl.setText("Gift Idea");

        Namelbl.setText("Name");

        Urllbl.setText("Url");

        List1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(List1);

        Textarea2.setColumns(20);
        Textarea2.setRows(5);
        Textarea2.setText("\n\n\n\n");
        jScrollPane3.setViewportView(Textarea2);

        Addbtn1.setText("ADD");
        Addbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Addbtn1ActionPerformed(evt);
            }
        });

        NameText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameText1ActionPerformed(evt);
            }
        });

        UrlText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UrlText1ActionPerformed(evt);
            }
        });

        Ideatext.setText("Idea 1");

        Idea2.setText("Idea 2");

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Delete2.setText("Delete");
        Delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete2ActionPerformed(evt);
            }
        });

        Addbtn2.setText("Add 2");
        Addbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Addbtn2ActionPerformed(evt);
            }
        });

        DisplayBtn1.setText("Display 1");
        DisplayBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayBtn1ActionPerformed(evt);
            }
        });

        DisplayBtn2.setText("Display 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Namelbl)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Giftlbl)
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Urllbl))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(NameText1)
                            .addComponent(UrlText1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Ideatext)
                                .addGap(172, 172, 172))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Idea2)
                                .addGap(177, 177, 177))
                            .addComponent(Ideatext2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Delete)
                                .addGap(155, 155, 155))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(IdeadText2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Delete2)
                .addGap(181, 181, 181))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Addbtn1)
                    .addComponent(DisplayBtn1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DisplayBtn2)
                    .addComponent(Addbtn2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Namelbl)
                            .addComponent(NameText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ideatext))
                        .addGap(18, 18, 18)
                        .addComponent(IdeadText2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Giftlbl)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Urllbl)
                            .addComponent(UrlText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(Delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Idea2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ideatext2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Delete2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addbtn1)
                    .addComponent(Addbtn2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DisplayBtn1)
                    .addComponent(DisplayBtn2))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void UrlText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UrlText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UrlText1ActionPerformed

    private void NameText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameText1ActionPerformed

    private void Addbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Addbtn1ActionPerformed
        // TODO add your handling code here:
        
        File outfile;
        FileWriter fw;
        BufferedWriter bw;
        String Iteam = IdeadText2.getText();
        
        try {
            outfile = new File("ChristmasShopping.txt");
            fw = new FileWriter(outfile,true);
            bw = new BufferedWriter(fw);
            
            bw.write(Iteam);
            bw.newLine();
            bw.close();
            JOptionPane.showMessageDialog(null,"Iteam Saved");
        }
        
        catch(IOException e){
            System.out.print("Error"+ e);
        }
        
        Name = NameText1.getText();
        Gift = Textarea2.getText();
        Url = UrlText1.getText();
        
        IdeadText2.setText( Name  +  Gift  +  Url );
    }//GEN-LAST:event_Addbtn1ActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
         Name = NameText1.getText();
        Gift = Textarea2.getText();
        Url = UrlText1.getText();
        
         IdeadText2.setText("");
    }//GEN-LAST:event_DeleteActionPerformed

    private void Addbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Addbtn2ActionPerformed
        // TODO add your handling code here:
          File outfile;
        FileWriter fw;
        BufferedWriter bw;
        String Iteam = Ideatext2.getText();
        
        try {
            outfile = new File("ChristmasShopping.txt");
            fw = new FileWriter(outfile,true);
            bw = new BufferedWriter(fw);
            
            bw.write(Iteam);
            bw.newLine();
            bw.close();
            JOptionPane.showMessageDialog(null,"Iteam Saved");
        }
        
        catch(IOException e){
            System.out.print("Error"+ e);
        }
         Name = NameText1.getText();
        Gift = Textarea2.getText();
        Url = UrlText1.getText();
        
        Ideatext2.setText( Name  +  Gift  +  Url );
    }//GEN-LAST:event_Addbtn2ActionPerformed

    private void Delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete2ActionPerformed
        // TODO add your handling code here:
          Name = NameText1.getText();
        Gift = Textarea2.getText();
        Url = UrlText1.getText();
        
        Ideatext2.setText("");
    }//GEN-LAST:event_Delete2ActionPerformed

    private void DisplayBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayBtn1ActionPerformed
        // TODO add your handling code here:
        File infile;
        FileReader fr;
        BufferedReader br;
        
        String Item;
        
        try{
            infile = new File ("ChristmasShopping.txt");
            fr = new FileReader(infile);
            br = new BufferedReader(fr);
            
            Item = br.readLine();
            while(Item!=null){
                
                JOptionPane.showMessageDialog(null, "Item" + Item);
                Item = br.readLine();
            }
            br.close();
        }
       
       catch(IOExpection e); {
           System.out.println(e);
       }
       
       catch(FileNOtFoundException ex; {
            System.out.println(e);
               
               }
       
       
       }
    }//GEN-LAST:event_DisplayBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChristmasShoppingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChristmasShoppingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChristmasShoppingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChristmasShoppingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChristmasShoppingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn1;
    private javax.swing.JButton Addbtn2;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Delete2;
    private javax.swing.JButton DisplayBtn1;
    private javax.swing.JButton DisplayBtn2;
    private javax.swing.JLabel Giftlbl;
    private javax.swing.JLabel Idea2;
    private javax.swing.JLabel IdeadText2;
    private javax.swing.JLabel Ideatext;
    private javax.swing.JLabel Ideatext2;
    private javax.swing.JList<String> List1;
    private javax.swing.JTextField NameText1;
    private javax.swing.JLabel Namelbl;
    private javax.swing.JTextArea Textarea2;
    private javax.swing.JTextField UrlText1;
    private javax.swing.JLabel Urllbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
